In [75]:
import random
import pandas as pd


df = pd.read_csv('ratings.txt', delim_whitespace=True,header=None,names=('Golfer', 'Mean', 'SD'))

def rounds():
    
    for round in range(3):
        for i in range(1, len(df)):
            df.iloc[i]['Mean'] = float(df.iloc[i]['Mean']) + random.normalvariate(float(df.iloc[i]['Mean']),float(df.iloc[i]['SD']))
            
    return df

def monte_carlo_simuation():



#random.normalvariate(68.99802084636,2.8022106094)

In [76]:
df

                      Golfer     Mean                 SD
0                     Golfer     Mean  Standarddeviation
1               SergioGarcia  536.442       2.8022106094
2                 TigerWoods  560.444       2.7891506279
3                 KennyPerry  559.382        2.779164583
4   GonzaloFernandez-Castano  562.261      2.80730658184
5                RoryMcIlroy  532.463      2.81525581752
6                   JohnCook  560.307        2.748840518
7                 JacoVanZyl   536.77      2.78426082931
8             BrandtSnedeker  568.421      2.77189131799
9          FrancescoMolinari  577.699      2.74834473201
10           MatteoManassero  558.886      2.77346484857
11              RoccoMediate  561.262      2.78827651594
12             PhilMickelson  566.893      2.77942880401
13                JustinRose  575.211      2.75785755538
14                  JimFuryk  565.045      2.74303206415
15                LukeDonald  574.678      2.75356932454
16               SouthAfrica  560.915        2.752106981
17           CharlSchwartzel  552.239      2.78476477706
18              DuffyWaldorf   564.09      2.75608325682
19            DarrenFichardt  563.852       2.7804524764
20                   JayHaas  576.853        2.712519019